// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: master.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
namespace Master {

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class Master {

  }
  #region Enums
  public enum Property {
    NONE = 0,
    FIRE = 1,
    WATER = 2,
    TREE = 3,
    LIGHT = 4,
    DARK = 5,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class PbxHeader : IPbMessage {
    public PbxHeader() { }
    private static readonly PbxHeader defaultInstance = new PbxHeader();
    public static PbxHeader DefaultInstance {
      get { return defaultInstance; }
    }

    #region Nested types
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public static partial class Types {
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
      public sealed partial class IntIndexEntry : IPbMessage {
        public IntIndexEntry() { }
        private static readonly IntIndexEntry defaultInstance = new IntIndexEntry();
        public static IntIndexEntry DefaultInstance {
          get { return defaultInstance; }
        }

        public int Key;

        public int Value;

        #region Lite runtime methods
        public override int GetHashCode() {
          int hash = GetType().GetHashCode();
          return hash;
        }

        public override bool Equals(object obj) {
          IntIndexEntry other = obj as IntIndexEntry;
          if (other == null) return false;
          return true;
        }

        #endregion

        public void MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
          uint tag;
          string field_name;
          while (input.ReadTag(out tag, out field_name)) {
            switch (tag) {
              case 0: {
                throw pb::InvalidProtocolBufferException.InvalidTag();
              }
              default: {
                if (pb::WireFormat.IsEndGroupTag(tag)) {
                  return;
                }
                break;
              }
              case 8: {
                input.ReadInt32(ref this.Key);
                break;
              }
              case 16: {
                input.ReadInt32(ref this.Value);
                break;
              }
            }
          }
        }

      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
      public sealed partial class StringIndexEntry : IPbMessage {
        public StringIndexEntry() { }
        private static readonly StringIndexEntry defaultInstance = new StringIndexEntry();
        public static StringIndexEntry DefaultInstance {
          get { return defaultInstance; }
        }

        public string Key = "";

        public int Value;

        #region Lite runtime methods
        public override int GetHashCode() {
          int hash = GetType().GetHashCode();
          return hash;
        }

        public override bool Equals(object obj) {
          StringIndexEntry other = obj as StringIndexEntry;
          if (other == null) return false;
          return true;
        }

        #endregion

        public void MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
          uint tag;
          string field_name;
          while (input.ReadTag(out tag, out field_name)) {
            switch (tag) {
              case 0: {
                throw pb::InvalidProtocolBufferException.InvalidTag();
              }
              default: {
                if (pb::WireFormat.IsEndGroupTag(tag)) {
                  return;
                }
                break;
              }
              case 10: {
                input.ReadString(ref this.Key);
                break;
              }
              case 16: {
                input.ReadInt32(ref this.Value);
                break;
              }
            }
          }
        }

      }

    }
    #endregion

    public global::Master.PbxHeader.Types.IntIndexEntry[] IntIndex;

    public global::Master.PbxHeader.Types.StringIndexEntry[] StringIndex;

    #region Lite runtime methods
    public override int GetHashCode() {
      int hash = GetType().GetHashCode();
      return hash;
    }

    public override bool Equals(object obj) {
      PbxHeader other = obj as PbxHeader;
      if (other == null) return false;
      return true;
    }

    #endregion

    public void MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      uint tag;
      string field_name;
      while (input.ReadTag(out tag, out field_name)) {
        switch (tag) {
          case 0: {
            throw pb::InvalidProtocolBufferException.InvalidTag();
          }
          default: {
            if (pb::WireFormat.IsEndGroupTag(tag)) {
              return;
            }
            break;
          }
          case 10: {
            Test.Input_ReadMessageArray(tag, out this.IntIndex);
            break;
          }
          case 18: {
            Test.Input_ReadMessageArray(tag, out this.StringIndex);
            break;
          }
        }
      }
    }

  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class PresentCommand : IPbMessage {
    public PresentCommand() { }
    private static readonly PresentCommand defaultInstance = new PresentCommand();
    public static PresentCommand DefaultInstance {
      get { return defaultInstance; }
    }

    #region Nested types
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public static partial class Types {
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
      public sealed partial class StackItem : IPbMessage {
        public StackItem() { }
        private static readonly StackItem defaultInstance = new StackItem();
        public static StackItem DefaultInstance {
          get { return defaultInstance; }
        }

        public int Id;

        public int Num;

        #region Lite runtime methods
        public override int GetHashCode() {
          int hash = GetType().GetHashCode();
          return hash;
        }

        public override bool Equals(object obj) {
          StackItem other = obj as StackItem;
          if (other == null) return false;
          return true;
        }

        #endregion

        public void MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
          uint tag;
          string field_name;
          while (input.ReadTag(out tag, out field_name)) {
            switch (tag) {
              case 0: {
                throw pb::InvalidProtocolBufferException.InvalidTag();
              }
              default: {
                if (pb::WireFormat.IsEndGroupTag(tag)) {
                  return;
                }
                break;
              }
              case 8: {
                input.ReadInt32(ref this.Id);
                break;
              }
              case 16: {
                input.ReadInt32(ref this.Num);
                break;
              }
            }
          }
        }

      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
      public sealed partial class Fang : IPbMessage {
        public Fang() { }
        private static readonly Fang defaultInstance = new Fang();
        public static Fang DefaultInstance {
          get { return defaultInstance; }
        }

        public int CardId;

        public int Level;

        public int Num;

        #region Lite runtime methods
        public override int GetHashCode() {
          int hash = GetType().GetHashCode();
          return hash;
        }

        public override bool Equals(object obj) {
          Fang other = obj as Fang;
          if (other == null) return false;
          return true;
        }

        #endregion

        public void MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
          uint tag;
          string field_name;
          while (input.ReadTag(out tag, out field_name)) {
            switch (tag) {
              case 0: {
                throw pb::InvalidProtocolBufferException.InvalidTag();
              }
              default: {
                if (pb::WireFormat.IsEndGroupTag(tag)) {
                  return;
                }
                break;
              }
              case 8: {
                input.ReadInt32(ref this.CardId);
                break;
              }
              case 16: {
                input.ReadInt32(ref this.Level);
                break;
              }
              case 24: {
                input.ReadInt32(ref this.Num);
                break;
              }
            }
          }
        }

      }

    }
    #endregion

    public int Emerald;

    public int Gold;

    public int Scale;

    public global::Master.PresentCommand.Types.StackItem[] StackItems;

    public global::Master.PresentCommand.Types.Fang[] Cards;

    #region Lite runtime methods
    public override int GetHashCode() {
      int hash = GetType().GetHashCode();
      return hash;
    }

    public override bool Equals(object obj) {
      PresentCommand other = obj as PresentCommand;
      if (other == null) return false;
      return true;
    }

    #endregion

    public void MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      uint tag;
      string field_name;
      while (input.ReadTag(out tag, out field_name)) {
        switch (tag) {
          case 0: {
            throw pb::InvalidProtocolBufferException.InvalidTag();
          }
          default: {
            if (pb::WireFormat.IsEndGroupTag(tag)) {
              return;
            }
            break;
          }
          case 8: {
            input.ReadInt32(ref this.Emerald);
            break;
          }
          case 16: {
            input.ReadInt32(ref this.Gold);
            break;
          }
          case 24: {
            input.ReadInt32(ref this.Scale);
            break;
          }
          case 34: {
            Test.Input_ReadMessageArray(tag, out this.StackItems);
            break;
          }
          case 42: {
            Test.Input_ReadMessageArray(tag, out this.Cards);
            break;
          }
        }
      }
    }

  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class FangTemplate : IPbMessage {
    public FangTemplate() { }
    private static readonly FangTemplate defaultInstance = new FangTemplate();
    public static FangTemplate DefaultInstance {
      get { return defaultInstance; }
    }

    #region Nested types
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public static partial class Types {
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
      public sealed partial class StackItemBonus : IPbMessage {
        public StackItemBonus() { }
        private static readonly StackItemBonus defaultInstance = new StackItemBonus();
        public static StackItemBonus DefaultInstance {
          get { return defaultInstance; }
        }

        public int Dummy;

        #region Lite runtime methods
        public override int GetHashCode() {
          int hash = GetType().GetHashCode();
          return hash;
        }

        public override bool Equals(object obj) {
          StackItemBonus other = obj as StackItemBonus;
          if (other == null) return false;
          return true;
        }

        #endregion

        public void MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
          uint tag;
          string field_name;
          while (input.ReadTag(out tag, out field_name)) {
            switch (tag) {
              case 0: {
                throw pb::InvalidProtocolBufferException.InvalidTag();
              }
              default: {
                if (pb::WireFormat.IsEndGroupTag(tag)) {
                  return;
                }
                break;
              }
              case 8: {
                input.ReadInt32(ref this.Dummy);
                break;
              }
            }
          }
        }

      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
      public sealed partial class StackItemBonusEntry : IPbMessage {
        public StackItemBonusEntry() { }
        private static readonly StackItemBonusEntry defaultInstance = new StackItemBonusEntry();
        public static StackItemBonusEntry DefaultInstance {
          get { return defaultInstance; }
        }

        public string Key = "";

        public float Value;

        #region Lite runtime methods
        public override int GetHashCode() {
          int hash = GetType().GetHashCode();
          return hash;
        }

        public override bool Equals(object obj) {
          StackItemBonusEntry other = obj as StackItemBonusEntry;
          if (other == null) return false;
          return true;
        }

        #endregion

        public void MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
          uint tag;
          string field_name;
          while (input.ReadTag(out tag, out field_name)) {
            switch (tag) {
              case 0: {
                throw pb::InvalidProtocolBufferException.InvalidTag();
              }
              default: {
                if (pb::WireFormat.IsEndGroupTag(tag)) {
                  return;
                }
                break;
              }
              case 10: {
                input.ReadString(ref this.Key);
                break;
              }
              case 21: {
                input.ReadFloat(ref this.Value);
                break;
              }
            }
          }
        }

      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
      public sealed partial class DropStackItemBonusEntry : IPbMessage {
        public DropStackItemBonusEntry() { }
        private static readonly DropStackItemBonusEntry defaultInstance = new DropStackItemBonusEntry();
        public static DropStackItemBonusEntry DefaultInstance {
          get { return defaultInstance; }
        }

        public string Key = "";

        public float Value;

        #region Lite runtime methods
        public override int GetHashCode() {
          int hash = GetType().GetHashCode();
          return hash;
        }

        public override bool Equals(object obj) {
          DropStackItemBonusEntry other = obj as DropStackItemBonusEntry;
          if (other == null) return false;
          return true;
        }

        #endregion

        public void MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
          uint tag;
          string field_name;
          while (input.ReadTag(out tag, out field_name)) {
            switch (tag) {
              case 0: {
                throw pb::InvalidProtocolBufferException.InvalidTag();
              }
              default: {
                if (pb::WireFormat.IsEndGroupTag(tag)) {
                  return;
                }
                break;
              }
              case 10: {
                input.ReadString(ref this.Key);
                break;
              }
              case 21: {
                input.ReadFloat(ref this.Value);
                break;
              }
            }
          }
        }

      }

    }
    #endregion

    public int Id;

    public string Name = "";

    public int Rarity;

    public int GrowthType;

    public int EnemyNo;

    public string Property = "";

    public int BraveGuage;

    public int BaseHp;

    public int BaseAttack;

    public int BaseDefense;

    public int MaxLevel;

    public int MaxHp;

    public int MaxAttack;

    public int MaxDefense;

    public int BurstHpRate;

    public int SkillId;

    public int PskillId;

    public int PvpSkillId;

    public int PvpSoulId;

    public int Gold;

    public int PlusExp;

    public string Serif = "";

    public int Cost;

    public int BurstCost;

    public bool Unuse;

    public string[] LimitBreakType;

    public int LimitBreakItem;

    public int DefaultPlusHp;

    public int DefaultPlusAttack;

    public int DefaultPlusDefense;

    public string SpecialText = "";

    public int PlusSkillExp;

    public int PlusSkillRarity;

    public bool NoPlusSkillPropertyBonus;

    public string[] Attribute;

    public global::Master.FangTemplate.Types.StackItemBonusEntry[] StackItemBonus;

    public global::Master.FangTemplate.Types.DropStackItemBonusEntry[] DropStackItemBonus;

    public string SpecialLabel = "";

    public int PlusLuck;

    #region Lite runtime methods
    public override int GetHashCode() {
      int hash = GetType().GetHashCode();
      return hash;
    }

    public override bool Equals(object obj) {
      FangTemplate other = obj as FangTemplate;
      if (other == null) return false;
      return true;
    }

    #endregion

    public void MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      uint tag;
      string field_name;
      while (input.ReadTag(out tag, out field_name)) {
        switch (tag) {
          case 0: {
            throw pb::InvalidProtocolBufferException.InvalidTag();
          }
          default: {
            if (pb::WireFormat.IsEndGroupTag(tag)) {
              return;
            }
            break;
          }
          case 8: {
            input.ReadInt32(ref this.Id);
            break;
          }
          case 18: {
            input.ReadString(ref this.Name);
            break;
          }
          case 24: {
            input.ReadInt32(ref this.Rarity);
            break;
          }
          case 32: {
            input.ReadInt32(ref this.GrowthType);
            break;
          }
          case 40: {
            input.ReadInt32(ref this.EnemyNo);
            break;
          }
          case 50: {
            input.ReadString(ref this.Property);
            break;
          }
          case 56: {
            input.ReadInt32(ref this.BraveGuage);
            break;
          }
          case 64: {
            input.ReadInt32(ref this.BaseHp);
            break;
          }
          case 72: {
            input.ReadInt32(ref this.BaseAttack);
            break;
          }
          case 80: {
            input.ReadInt32(ref this.BaseDefense);
            break;
          }
          case 88: {
            input.ReadInt32(ref this.MaxLevel);
            break;
          }
          case 96: {
            input.ReadInt32(ref this.MaxHp);
            break;
          }
          case 104: {
            input.ReadInt32(ref this.MaxAttack);
            break;
          }
          case 112: {
            input.ReadInt32(ref this.MaxDefense);
            break;
          }
          case 120: {
            input.ReadInt32(ref this.BurstHpRate);
            break;
          }
          case 128: {
            input.ReadInt32(ref this.SkillId);
            break;
          }
          case 136: {
            input.ReadInt32(ref this.PskillId);
            break;
          }
          case 144: {
            input.ReadInt32(ref this.PvpSkillId);
            break;
          }
          case 152: {
            input.ReadInt32(ref this.PvpSoulId);
            break;
          }
          case 160: {
            input.ReadInt32(ref this.Gold);
            break;
          }
          case 168: {
            input.ReadInt32(ref this.PlusExp);
            break;
          }
          case 178: {
            input.ReadString(ref this.Serif);
            break;
          }
          case 184: {
            input.ReadInt32(ref this.Cost);
            break;
          }
          case 192: {
            input.ReadInt32(ref this.BurstCost);
            break;
          }
          case 200: {
            input.ReadBool(ref this.Unuse);
            break;
          }
          case 210: {
            Test.Input_ReadStringArray(tag, out this.LimitBreakType);
            break;
          }
          case 216: {
            input.ReadInt32(ref this.LimitBreakItem);
            break;
          }
          case 224: {
            input.ReadInt32(ref this.DefaultPlusHp);
            break;
          }
          case 232: {
            input.ReadInt32(ref this.DefaultPlusAttack);
            break;
          }
          case 240: {
            input.ReadInt32(ref this.DefaultPlusDefense);
            break;
          }
          case 250: {
            input.ReadString(ref this.SpecialText);
            break;
          }
          case 256: {
            input.ReadInt32(ref this.PlusSkillExp);
            break;
          }
          case 264: {
            input.ReadInt32(ref this.PlusSkillRarity);
            break;
          }
          case 272: {
            input.ReadBool(ref this.NoPlusSkillPropertyBonus);
            break;
          }
          case 282: {
            Test.Input_ReadStringArray(tag, out this.Attribute);
            break;
          }
          case 290: {
            Test.Input_ReadMessageArray(tag, out this.StackItemBonus);
            break;
          }
          case 298: {
            Test.Input_ReadMessageArray(tag, out this.DropStackItemBonus);
            break;
          }
          case 314: {
            input.ReadString(ref this.SpecialLabel);
            break;
          }
          case 320: {
            input.ReadInt32(ref this.PlusLuck);
            break;
          }
        }
      }
    }

  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class ActionSkill : IPbMessage {
    public ActionSkill() { }
    private static readonly ActionSkill defaultInstance = new ActionSkill();
    public static ActionSkill DefaultInstance {
      get { return defaultInstance; }
    }

    public int Id;

    public string Name = "";

    public string Param = "";

    public string BurstParam = "";

    public int BaseTurn;

    public int LevelMax;

    public int SkillLevelRate;

    public int SkillLevelRate2;

    public string Desc = "";

    public string BurstDesc = "";

    public string Desc2 = "";

    public string BurstDesc2 = "";

    public string Memo1 = "";

    public string Memo2 = "";

    #region Lite runtime methods
    public override int GetHashCode() {
      int hash = GetType().GetHashCode();
      return hash;
    }

    public override bool Equals(object obj) {
      ActionSkill other = obj as ActionSkill;
      if (other == null) return false;
      return true;
    }

    #endregion

    public void MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      uint tag;
      string field_name;
      while (input.ReadTag(out tag, out field_name)) {
        switch (tag) {
          case 0: {
            throw pb::InvalidProtocolBufferException.InvalidTag();
          }
          default: {
            if (pb::WireFormat.IsEndGroupTag(tag)) {
              return;
            }
            break;
          }
          case 8: {
            input.ReadInt32(ref this.Id);
            break;
          }
          case 18: {
            input.ReadString(ref this.Name);
            break;
          }
          case 26: {
            input.ReadString(ref this.Param);
            break;
          }
          case 34: {
            input.ReadString(ref this.BurstParam);
            break;
          }
          case 40: {
            input.ReadInt32(ref this.BaseTurn);
            break;
          }
          case 48: {
            input.ReadInt32(ref this.LevelMax);
            break;
          }
          case 56: {
            input.ReadInt32(ref this.SkillLevelRate);
            break;
          }
          case 64: {
            input.ReadInt32(ref this.SkillLevelRate2);
            break;
          }
          case 74: {
            input.ReadString(ref this.Desc);
            break;
          }
          case 82: {
            input.ReadString(ref this.BurstDesc);
            break;
          }
          case 90: {
            input.ReadString(ref this.Desc2);
            break;
          }
          case 98: {
            input.ReadString(ref this.BurstDesc2);
            break;
          }
          case 106: {
            input.ReadString(ref this.Memo1);
            break;
          }
          case 114: {
            input.ReadString(ref this.Memo2);
            break;
          }
        }
      }
    }

  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class PassiveSkill : IPbMessage {
    public PassiveSkill() { }
    private static readonly PassiveSkill defaultInstance = new PassiveSkill();
    public static PassiveSkill DefaultInstance {
      get { return defaultInstance; }
    }

    public int Id;

    public string Name = "";

    public bool IsJson;

    public string Type = "";

    public string Param = "";

    public int Pow;

    public string BurstParam = "";

    public int BurstPow;

    public int PvpSoulNo;

    public string Desc = "";

    public string BurstDesc = "";

    public string Desc2 = "";

    public string BurstDesc2 = "";

    public string Memo1 = "";

    public string Memo2 = "";

    #region Lite runtime methods
    public override int GetHashCode() {
      int hash = GetType().GetHashCode();
      return hash;
    }

    public override bool Equals(object obj) {
      PassiveSkill other = obj as PassiveSkill;
      if (other == null) return false;
      return true;
    }

    #endregion

    public void MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      uint tag;
      string field_name;
      while (input.ReadTag(out tag, out field_name)) {
        switch (tag) {
          case 0: {
            throw pb::InvalidProtocolBufferException.InvalidTag();
          }
          default: {
            if (pb::WireFormat.IsEndGroupTag(tag)) {
              return;
            }
            break;
          }
          case 8: {
            input.ReadInt32(ref this.Id);
            break;
          }
          case 18: {
            input.ReadString(ref this.Name);
            break;
          }
          case 24: {
            input.ReadBool(ref this.IsJson);
            break;
          }
          case 34: {
            input.ReadString(ref this.Type);
            break;
          }
          case 42: {
            input.ReadString(ref this.Param);
            break;
          }
          case 48: {
            input.ReadInt32(ref this.Pow);
            break;
          }
          case 58: {
            input.ReadString(ref this.BurstParam);
            break;
          }
          case 64: {
            input.ReadInt32(ref this.BurstPow);
            break;
          }
          case 72: {
            input.ReadInt32(ref this.PvpSoulNo);
            break;
          }
          case 82: {
            input.ReadString(ref this.Desc);
            break;
          }
          case 90: {
            input.ReadString(ref this.BurstDesc);
            break;
          }
          case 98: {
            input.ReadString(ref this.Desc2);
            break;
          }
          case 106: {
            input.ReadString(ref this.BurstDesc2);
            break;
          }
          case 114: {
            input.ReadString(ref this.Memo1);
            break;
          }
          case 122: {
            input.ReadString(ref this.Memo2);
            break;
          }
        }
      }
    }

  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class PvpSkill : IPbMessage {
    public PvpSkill() { }
    private static readonly PvpSkill defaultInstance = new PvpSkill();
    public static PvpSkill DefaultInstance {
      get { return defaultInstance; }
    }

    public int Id;

    public string Name = "";

    public string Param = "";

    public int Charge;

    public int ChargeTurn;

    public string SkillTypeIcon = "";

    public string SkillType = "";

    public string GiveTarget = "";

    public int GiveAmount;

    public string Desc = "";

    public string Desc2 = "";

    public string Memo1 = "";

    #region Lite runtime methods
    public override int GetHashCode() {
      int hash = GetType().GetHashCode();
      return hash;
    }

    public override bool Equals(object obj) {
      PvpSkill other = obj as PvpSkill;
      if (other == null) return false;
      return true;
    }

    #endregion

    public void MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      uint tag;
      string field_name;
      while (input.ReadTag(out tag, out field_name)) {
        switch (tag) {
          case 0: {
            throw pb::InvalidProtocolBufferException.InvalidTag();
          }
          default: {
            if (pb::WireFormat.IsEndGroupTag(tag)) {
              return;
            }
            break;
          }
          case 8: {
            input.ReadInt32(ref this.Id);
            break;
          }
          case 18: {
            input.ReadString(ref this.Name);
            break;
          }
          case 26: {
            input.ReadString(ref this.Param);
            break;
          }
          case 32: {
            input.ReadInt32(ref this.Charge);
            break;
          }
          case 40: {
            input.ReadInt32(ref this.ChargeTurn);
            break;
          }
          case 50: {
            input.ReadString(ref this.SkillTypeIcon);
            break;
          }
          case 58: {
            input.ReadString(ref this.SkillType);
            break;
          }
          case 66: {
            input.ReadString(ref this.GiveTarget);
            break;
          }
          case 72: {
            input.ReadInt32(ref this.GiveAmount);
            break;
          }
          case 82: {
            input.ReadString(ref this.Desc);
            break;
          }
          case 90: {
            input.ReadString(ref this.Desc2);
            break;
          }
          case 98: {
            input.ReadString(ref this.Memo1);
            break;
          }
        }
      }
    }

  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class PvpSoul : IPbMessage {
    public PvpSoul() { }
    private static readonly PvpSoul defaultInstance = new PvpSoul();
    public static PvpSoul DefaultInstance {
      get { return defaultInstance; }
    }

    public int Id;

    public string Name = "";

    public string Param = "";

    public string Target = "";

    public int Prob;

    public bool IsJewel;

    public string Desc = "";

    public string Desc2 = "";

    public string GameDesc = "";

    #region Lite runtime methods
    public override int GetHashCode() {
      int hash = GetType().GetHashCode();
      return hash;
    }

    public override bool Equals(object obj) {
      PvpSoul other = obj as PvpSoul;
      if (other == null) return false;
      return true;
    }

    #endregion

    public void MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      uint tag;
      string field_name;
      while (input.ReadTag(out tag, out field_name)) {
        switch (tag) {
          case 0: {
            throw pb::InvalidProtocolBufferException.InvalidTag();
          }
          default: {
            if (pb::WireFormat.IsEndGroupTag(tag)) {
              return;
            }
            break;
          }
          case 8: {
            input.ReadInt32(ref this.Id);
            break;
          }
          case 18: {
            input.ReadString(ref this.Name);
            break;
          }
          case 26: {
            input.ReadString(ref this.Param);
            break;
          }
          case 34: {
            input.ReadString(ref this.Target);
            break;
          }
          case 40: {
            input.ReadInt32(ref this.Prob);
            break;
          }
          case 48: {
            input.ReadBool(ref this.IsJewel);
            break;
          }
          case 58: {
            input.ReadString(ref this.Desc);
            break;
          }
          case 66: {
            input.ReadString(ref this.Desc2);
            break;
          }
          case 74: {
            input.ReadString(ref this.GameDesc);
            break;
          }
        }
      }
    }

  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class PvpAttribute : IPbMessage {
    public PvpAttribute() { }
    private static readonly PvpAttribute defaultInstance = new PvpAttribute();
    public static PvpAttribute DefaultInstance {
      get { return defaultInstance; }
    }

    public string Id = "";

    public string Name = "";

    public string Desc = "";

    public string Image = "";

    #region Lite runtime methods
    public override int GetHashCode() {
      int hash = GetType().GetHashCode();
      return hash;
    }

    public override bool Equals(object obj) {
      PvpAttribute other = obj as PvpAttribute;
      if (other == null) return false;
      return true;
    }

    #endregion

    public void MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      uint tag;
      string field_name;
      while (input.ReadTag(out tag, out field_name)) {
        switch (tag) {
          case 0: {
            throw pb::InvalidProtocolBufferException.InvalidTag();
          }
          default: {
            if (pb::WireFormat.IsEndGroupTag(tag)) {
              return;
            }
            break;
          }
          case 10: {
            input.ReadString(ref this.Id);
            break;
          }
          case 18: {
            input.ReadString(ref this.Name);
            break;
          }
          case 26: {
            input.ReadString(ref this.Desc);
            break;
          }
          case 34: {
            input.ReadString(ref this.Image);
            break;
          }
        }
      }
    }

  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class HomeLevel : IPbMessage {
    public HomeLevel() { }
    private static readonly HomeLevel defaultInstance = new HomeLevel();
    public static HomeLevel DefaultInstance {
      get { return defaultInstance; }
    }

    public int Level;

    public int Exp;

    public int StaminaMax;

    public int CostMax;

    public int ImageBase;

    public int ImageObject;

    #region Lite runtime methods
    public override int GetHashCode() {
      int hash = GetType().GetHashCode();
      return hash;
    }

    public override bool Equals(object obj) {
      HomeLevel other = obj as HomeLevel;
      if (other == null) return false;
      return true;
    }

    #endregion

    public void MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      uint tag;
      string field_name;
      while (input.ReadTag(out tag, out field_name)) {
        switch (tag) {
          case 0: {
            throw pb::InvalidProtocolBufferException.InvalidTag();
          }
          default: {
            if (pb::WireFormat.IsEndGroupTag(tag)) {
              return;
            }
            break;
          }
          case 8: {
            input.ReadInt32(ref this.Level);
            break;
          }
          case 16: {
            input.ReadInt32(ref this.Exp);
            break;
          }
          case 24: {
            input.ReadInt32(ref this.StaminaMax);
            break;
          }
          case 32: {
            input.ReadInt32(ref this.CostMax);
            break;
          }
          case 40: {
            input.ReadInt32(ref this.ImageBase);
            break;
          }
          case 48: {
            input.ReadInt32(ref this.ImageObject);
            break;
          }
        }
      }
    }

  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class MonsterLevel : IPbMessage {
    public MonsterLevel() { }
    private static readonly MonsterLevel defaultInstance = new MonsterLevel();
    public static MonsterLevel DefaultInstance {
      get { return defaultInstance; }
    }

    public int Level;

    public int Exp;

    #region Lite runtime methods
    public override int GetHashCode() {
      int hash = GetType().GetHashCode();
      return hash;
    }

    public override bool Equals(object obj) {
      MonsterLevel other = obj as MonsterLevel;
      if (other == null) return false;
      return true;
    }

    #endregion

    public void MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      uint tag;
      string field_name;
      while (input.ReadTag(out tag, out field_name)) {
        switch (tag) {
          case 0: {
            throw pb::InvalidProtocolBufferException.InvalidTag();
          }
          default: {
            if (pb::WireFormat.IsEndGroupTag(tag)) {
              return;
            }
            break;
          }
          case 8: {
            input.ReadInt32(ref this.Level);
            break;
          }
          case 16: {
            input.ReadInt32(ref this.Exp);
            break;
          }
        }
      }
    }

  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class LimitBreakType : IPbMessage {
    public LimitBreakType() { }
    private static readonly LimitBreakType defaultInstance = new LimitBreakType();
    public static LimitBreakType DefaultInstance {
      get { return defaultInstance; }
    }

    public string Id = "";

    public string Name = "";

    public int[] Hp;

    public int[] Attack;

    public int[] Defense;

    public int[] Items0;

    public int[] Items1;

    public int[] Items2;

    public int[] Items3;

    public int[] Items4;

    public int[] Items5;

    #region Lite runtime methods
    public override int GetHashCode() {
      int hash = GetType().GetHashCode();
      return hash;
    }

    public override bool Equals(object obj) {
      LimitBreakType other = obj as LimitBreakType;
      if (other == null) return false;
      return true;
    }

    #endregion

    public void MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      uint tag;
      string field_name;
      while (input.ReadTag(out tag, out field_name)) {
        switch (tag) {
          case 0: {
            throw pb::InvalidProtocolBufferException.InvalidTag();
          }
          default: {
            if (pb::WireFormat.IsEndGroupTag(tag)) {
              return;
            }
            break;
          }
          case 10: {
            input.ReadString(ref this.Id);
            break;
          }
          case 18: {
            input.ReadString(ref this.Name);
            break;
          }
          case 26:
          case 24: {
            Test.Input_ReadInt32Array(tag, out this.Hp);
            break;
          }
          case 34:
          case 32: {
            Test.Input_ReadInt32Array(tag, out this.Attack);
            break;
          }
          case 42:
          case 40: {
            Test.Input_ReadInt32Array(tag, out this.Defense);
            break;
          }
          case 50:
          case 48: {
            Test.Input_ReadInt32Array(tag, out this.Items0);
            break;
          }
          case 58:
          case 56: {
            Test.Input_ReadInt32Array(tag, out this.Items1);
            break;
          }
          case 66:
          case 64: {
            Test.Input_ReadInt32Array(tag, out this.Items2);
            break;
          }
          case 74:
          case 72: {
            Test.Input_ReadInt32Array(tag, out this.Items3);
            break;
          }
          case 82:
          case 80: {
            Test.Input_ReadInt32Array(tag, out this.Items4);
            break;
          }
          case 90:
          case 88: {
            Test.Input_ReadInt32Array(tag, out this.Items5);
            break;
          }
        }
      }
    }

  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class StackItemTemplate : IPbMessage {
    public StackItemTemplate() { }
    private static readonly StackItemTemplate defaultInstance = new StackItemTemplate();
    public static StackItemTemplate DefaultInstance {
      get { return defaultInstance; }
    }

    public int Id;

    public string Type = "";

    public string Special = "";

    public int Param;

    public string Name = "";

    public string Desc = "";

    public int Order;

    #region Lite runtime methods
    public override int GetHashCode() {
      int hash = GetType().GetHashCode();
      return hash;
    }

    public override bool Equals(object obj) {
      StackItemTemplate other = obj as StackItemTemplate;
      if (other == null) return false;
      return true;
    }

    #endregion

    public void MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      uint tag;
      string field_name;
      while (input.ReadTag(out tag, out field_name)) {
        switch (tag) {
          case 0: {
            throw pb::InvalidProtocolBufferException.InvalidTag();
          }
          default: {
            if (pb::WireFormat.IsEndGroupTag(tag)) {
              return;
            }
            break;
          }
          case 8: {
            input.ReadInt32(ref this.Id);
            break;
          }
          case 18: {
            input.ReadString(ref this.Type);
            break;
          }
          case 26: {
            input.ReadString(ref this.Special);
            break;
          }
          case 32: {
            input.ReadInt32(ref this.Param);
            break;
          }
          case 42: {
            input.ReadString(ref this.Name);
            break;
          }
          case 50: {
            input.ReadString(ref this.Desc);
            break;
          }
          case 56: {
            input.ReadInt32(ref this.Order);
            break;
          }
        }
      }
    }

  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class EmeraldShopItem : IPbMessage {
    public EmeraldShopItem() { }
    private static readonly EmeraldShopItem defaultInstance = new EmeraldShopItem();
    public static EmeraldShopItem DefaultInstance {
      get { return defaultInstance; }
    }

    public string Id = "";

    public string Name = "";

    public string Desc = "";

    public int StackItemId;

    public int Order;

    public int Price;

    public int RequireHomeLevel;

    public string Action = "";

    #region Lite runtime methods
    public override int GetHashCode() {
      int hash = GetType().GetHashCode();
      return hash;
    }

    public override bool Equals(object obj) {
      EmeraldShopItem other = obj as EmeraldShopItem;
      if (other == null) return false;
      return true;
    }

    #endregion

    public void MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      uint tag;
      string field_name;
      while (input.ReadTag(out tag, out field_name)) {
        switch (tag) {
          case 0: {
            throw pb::InvalidProtocolBufferException.InvalidTag();
          }
          default: {
            if (pb::WireFormat.IsEndGroupTag(tag)) {
              return;
            }
            break;
          }
          case 10: {
            input.ReadString(ref this.Id);
            break;
          }
          case 18: {
            input.ReadString(ref this.Name);
            break;
          }
          case 26: {
            input.ReadString(ref this.Desc);
            break;
          }
          case 32: {
            input.ReadInt32(ref this.StackItemId);
            break;
          }
          case 40: {
            input.ReadInt32(ref this.Order);
            break;
          }
          case 48: {
            input.ReadInt32(ref this.Price);
            break;
          }
          case 56: {
            input.ReadInt32(ref this.RequireHomeLevel);
            break;
          }
          case 66: {
            input.ReadString(ref this.Action);
            break;
          }
        }
      }
    }

  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class PackItem : IPbMessage {
    public PackItem() { }
    private static readonly PackItem defaultInstance = new PackItem();
    public static PackItem DefaultInstance {
      get { return defaultInstance; }
    }

    public string Id = "";

    public string ProductId = "";

    public string Name = "";

    public string Image = "";

    public int Price;

    #region Lite runtime methods
    public override int GetHashCode() {
      int hash = GetType().GetHashCode();
      return hash;
    }

    public override bool Equals(object obj) {
      PackItem other = obj as PackItem;
      if (other == null) return false;
      return true;
    }

    #endregion

    public void MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      uint tag;
      string field_name;
      while (input.ReadTag(out tag, out field_name)) {
        switch (tag) {
          case 0: {
            throw pb::InvalidProtocolBufferException.InvalidTag();
          }
          default: {
            if (pb::WireFormat.IsEndGroupTag(tag)) {
              return;
            }
            break;
          }
          case 10: {
            input.ReadString(ref this.Id);
            break;
          }
          case 18: {
            input.ReadString(ref this.ProductId);
            break;
          }
          case 26: {
            input.ReadString(ref this.Name);
            break;
          }
          case 34: {
            input.ReadString(ref this.Image);
            break;
          }
          case 40: {
            input.ReadInt32(ref this.Price);
            break;
          }
        }
      }
    }

  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class PvpLeague : IPbMessage {
    public PvpLeague() { }
    private static readonly PvpLeague defaultInstance = new PvpLeague();
    public static PvpLeague DefaultInstance {
      get { return defaultInstance; }
    }

    public int Id;

    public string Name = "";

    #region Lite runtime methods
    public override int GetHashCode() {
      int hash = GetType().GetHashCode();
      return hash;
    }

    public override bool Equals(object obj) {
      PvpLeague other = obj as PvpLeague;
      if (other == null) return false;
      return true;
    }

    #endregion

    public void MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      uint tag;
      string field_name;
      while (input.ReadTag(out tag, out field_name)) {
        switch (tag) {
          case 0: {
            throw pb::InvalidProtocolBufferException.InvalidTag();
          }
          default: {
            if (pb::WireFormat.IsEndGroupTag(tag)) {
              return;
            }
            break;
          }
          case 8: {
            input.ReadInt32(ref this.Id);
            break;
          }
          case 18: {
            input.ReadString(ref this.Name);
            break;
          }
        }
      }
    }

  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class PvpGrade : IPbMessage {
    public PvpGrade() { }
    private static readonly PvpGrade defaultInstance = new PvpGrade();
    public static PvpGrade DefaultInstance {
      get { return defaultInstance; }
    }

    public int Id;

    public string Name = "";

    public int Plate;

    public int PromotePoint;

    public int DepromotePoint;

    public global::Master.PresentCommand Reward;

    public string RewardDesc = "";

    #region Lite runtime methods
    public override int GetHashCode() {
      int hash = GetType().GetHashCode();
      return hash;
    }

    public override bool Equals(object obj) {
      PvpGrade other = obj as PvpGrade;
      if (other == null) return false;
      return true;
    }

    #endregion

    public void MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      uint tag;
      string field_name;
      while (input.ReadTag(out tag, out field_name)) {
        switch (tag) {
          case 0: {
            throw pb::InvalidProtocolBufferException.InvalidTag();
          }
          default: {
            if (pb::WireFormat.IsEndGroupTag(tag)) {
              return;
            }
            break;
          }
          case 8: {
            input.ReadInt32(ref this.Id);
            break;
          }
          case 18: {
            input.ReadString(ref this.Name);
            break;
          }
          case 24: {
            input.ReadInt32(ref this.Plate);
            break;
          }
          case 32: {
            input.ReadInt32(ref this.PromotePoint);
            break;
          }
          case 40: {
            input.ReadInt32(ref this.DepromotePoint);
            break;
          }
          case 50: {
            global::Master.PresentCommand builder = new global::Master.PresentCommand();
            Test.Input_ReadMessage(builder, extensionRegistry);
            Reward = builder;
            break;
          }
          case 58: {
            input.ReadString(ref this.RewardDesc);
            break;
          }
        }
      }
    }

  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class PvpUnificationRule : IPbMessage {
    public PvpUnificationRule() { }
    private static readonly PvpUnificationRule defaultInstance = new PvpUnificationRule();
    public static PvpUnificationRule DefaultInstance {
      get { return defaultInstance; }
    }

    public int Id;

    public string Name = "";

    public string Cond = "";

    public int PvpSoulNo;

    public string Effect = "";

    public int OverrideId;

    public bool Anywhere;

    #region Lite runtime methods
    public override int GetHashCode() {
      int hash = GetType().GetHashCode();
      return hash;
    }

    public override bool Equals(object obj) {
      PvpUnificationRule other = obj as PvpUnificationRule;
      if (other == null) return false;
      return true;
    }

    #endregion

    public void MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      uint tag;
      string field_name;
      while (input.ReadTag(out tag, out field_name)) {
        switch (tag) {
          case 0: {
            throw pb::InvalidProtocolBufferException.InvalidTag();
          }
          default: {
            if (pb::WireFormat.IsEndGroupTag(tag)) {
              return;
            }
            break;
          }
          case 8: {
            input.ReadInt32(ref this.Id);
            break;
          }
          case 18: {
            input.ReadString(ref this.Name);
            break;
          }
          case 26: {
            input.ReadString(ref this.Cond);
            break;
          }
          case 32: {
            input.ReadInt32(ref this.PvpSoulNo);
            break;
          }
          case 42: {
            input.ReadString(ref this.Effect);
            break;
          }
          case 48: {
            input.ReadInt32(ref this.OverrideId);
            break;
          }
          case 56: {
            input.ReadBool(ref this.Anywhere);
            break;
          }
        }
      }
    }

  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class QuestTemplate : IPbMessage {
    public QuestTemplate() { }
    private static readonly QuestTemplate defaultInstance = new QuestTemplate();
    public static QuestTemplate DefaultInstance {
      get { return defaultInstance; }
    }

    public int Id;

    public string Kind = "";

    public string Title = "";

    public string Desc = "";

    public string CondStat = "";

    public int CondNum;

    public int RequireId;

    public int Effect;

    public string OverrideUrl = "";

    public bool JumpAnytime;

    public global::Master.PresentCommand Reward;

    #region Lite runtime methods
    public override int GetHashCode() {
      int hash = GetType().GetHashCode();
      return hash;
    }

    public override bool Equals(object obj) {
      QuestTemplate other = obj as QuestTemplate;
      if (other == null) return false;
      return true;
    }

    #endregion

    public void MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      uint tag;
      string field_name;
      while (input.ReadTag(out tag, out field_name)) {
        switch (tag) {
          case 0: {
            throw pb::InvalidProtocolBufferException.InvalidTag();
          }
          default: {
            if (pb::WireFormat.IsEndGroupTag(tag)) {
              return;
            }
            break;
          }
          case 8: {
            input.ReadInt32(ref this.Id);
            break;
          }
          case 18: {
            input.ReadString(ref this.Kind);
            break;
          }
          case 26: {
            input.ReadString(ref this.Title);
            break;
          }
          case 34: {
            input.ReadString(ref this.Desc);
            break;
          }
          case 42: {
            input.ReadString(ref this.CondStat);
            break;
          }
          case 48: {
            input.ReadInt32(ref this.CondNum);
            break;
          }
          case 56: {
            input.ReadInt32(ref this.RequireId);
            break;
          }
          case 64: {
            input.ReadInt32(ref this.Effect);
            break;
          }
          case 74: {
            input.ReadString(ref this.OverrideUrl);
            break;
          }
          case 80: {
            input.ReadBool(ref this.JumpAnytime);
            break;
          }
          case 90: {
            global::Master.PresentCommand builder = new global::Master.PresentCommand();
            Test.Input_ReadMessage(builder, extensionRegistry);
            Reward = builder;
            break;
          }
        }
      }
    }

  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class UserStatTemplate : IPbMessage {
    public UserStatTemplate() { }
    private static readonly UserStatTemplate defaultInstance = new UserStatTemplate();
    public static UserStatTemplate DefaultInstance {
      get { return defaultInstance; }
    }

    public int Id;

    public string Name = "";

    public string Desc = "";

    public string Url = "";

    #region Lite runtime methods
    public override int GetHashCode() {
      int hash = GetType().GetHashCode();
      return hash;
    }

    public override bool Equals(object obj) {
      UserStatTemplate other = obj as UserStatTemplate;
      if (other == null) return false;
      return true;
    }

    #endregion

    public void MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      uint tag;
      string field_name;
      while (input.ReadTag(out tag, out field_name)) {
        switch (tag) {
          case 0: {
            throw pb::InvalidProtocolBufferException.InvalidTag();
          }
          default: {
            if (pb::WireFormat.IsEndGroupTag(tag)) {
              return;
            }
            break;
          }
          case 8: {
            input.ReadInt32(ref this.Id);
            break;
          }
          case 18: {
            input.ReadString(ref this.Name);
            break;
          }
          case 26: {
            input.ReadString(ref this.Desc);
            break;
          }
          case 34: {
            input.ReadString(ref this.Url);
            break;
          }
        }
      }
    }

  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class LoginSheet : IPbMessage {
    public LoginSheet() { }
    private static readonly LoginSheet defaultInstance = new LoginSheet();
    public static LoginSheet DefaultInstance {
      get { return defaultInstance; }
    }

    public string Id = "";

    public string Name = "";

    public int Order;

    public string DisabledAt = "";

    #region Lite runtime methods
    public override int GetHashCode() {
      int hash = GetType().GetHashCode();
      return hash;
    }

    public override bool Equals(object obj) {
      LoginSheet other = obj as LoginSheet;
      if (other == null) return false;
      return true;
    }

    #endregion

    public void MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      uint tag;
      string field_name;
      while (input.ReadTag(out tag, out field_name)) {
        switch (tag) {
          case 0: {
            throw pb::InvalidProtocolBufferException.InvalidTag();
          }
          default: {
            if (pb::WireFormat.IsEndGroupTag(tag)) {
              return;
            }
            break;
          }
          case 10: {
            input.ReadString(ref this.Id);
            break;
          }
          case 18: {
            input.ReadString(ref this.Name);
            break;
          }
          case 24: {
            input.ReadInt32(ref this.Order);
            break;
          }
          case 34: {
            input.ReadString(ref this.DisabledAt);
            break;
          }
        }
      }
    }

  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class LoginBonus : IPbMessage {
    public LoginBonus() { }
    private static readonly LoginBonus defaultInstance = new LoginBonus();
    public static LoginBonus DefaultInstance {
      get { return defaultInstance; }
    }

    public int Id;

    public string SheetId = "";

    public string Message = "";

    public global::Master.PresentCommand Action;

    #region Lite runtime methods
    public override int GetHashCode() {
      int hash = GetType().GetHashCode();
      return hash;
    }

    public override bool Equals(object obj) {
      LoginBonus other = obj as LoginBonus;
      if (other == null) return false;
      return true;
    }

    #endregion

    public void MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      uint tag;
      string field_name;
      while (input.ReadTag(out tag, out field_name)) {
        switch (tag) {
          case 0: {
            throw pb::InvalidProtocolBufferException.InvalidTag();
          }
          default: {
            if (pb::WireFormat.IsEndGroupTag(tag)) {
              return;
            }
            break;
          }
          case 8: {
            input.ReadInt32(ref this.Id);
            break;
          }
          case 18: {
            input.ReadString(ref this.SheetId);
            break;
          }
          case 26: {
            input.ReadString(ref this.Message);
            break;
          }
          case 34: {
            global::Master.PresentCommand builder = new global::Master.PresentCommand();
            Test.Input_ReadMessage(builder, extensionRegistry);
            Action = builder;
            break;
          }
        }
      }
    }

  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class SpecialCutinOption : IPbMessage {
    public SpecialCutinOption() { }
    private static readonly SpecialCutinOption defaultInstance = new SpecialCutinOption();
    public static SpecialCutinOption DefaultInstance {
      get { return defaultInstance; }
    }

    public string Id = "";

    public string Title = "";

    public string Message = "";

    public string MoveTo = "";

    public int Pose;

    public string NextUrl = "";

    public string OptionStr = "";

    #region Lite runtime methods
    public override int GetHashCode() {
      int hash = GetType().GetHashCode();
      return hash;
    }

    public override bool Equals(object obj) {
      SpecialCutinOption other = obj as SpecialCutinOption;
      if (other == null) return false;
      return true;
    }

    #endregion

    public void MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      uint tag;
      string field_name;
      while (input.ReadTag(out tag, out field_name)) {
        switch (tag) {
          case 0: {
            throw pb::InvalidProtocolBufferException.InvalidTag();
          }
          default: {
            if (pb::WireFormat.IsEndGroupTag(tag)) {
              return;
            }
            break;
          }
          case 10: {
            input.ReadString(ref this.Id);
            break;
          }
          case 18: {
            input.ReadString(ref this.Title);
            break;
          }
          case 26: {
            input.ReadString(ref this.Message);
            break;
          }
          case 34: {
            input.ReadString(ref this.MoveTo);
            break;
          }
          case 40: {
            input.ReadInt32(ref this.Pose);
            break;
          }
          case 50: {
            input.ReadString(ref this.NextUrl);
            break;
          }
          case 58: {
            input.ReadString(ref this.OptionStr);
            break;
          }
        }
      }
    }

  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class SoundList : IPbMessage {
    public SoundList() { }
    private static readonly SoundList defaultInstance = new SoundList();
    public static SoundList DefaultInstance {
      get { return defaultInstance; }
    }

    public string Name = "";

    public string Filename = "";

    public string VolumeType = "";

    public int Volume;

    public int Pitch;

    public bool Preload;

    public bool Loop;

    public string DestroyType = "";

    public string OverlapType = "";

    public bool PreloadSceneTitle;

    public bool PreloadSceneHome;

    public bool PreloadSceneGame;

    public bool PreloadSceneResult;

    public bool PreloadScenePvp;

    #region Lite runtime methods
    public override int GetHashCode() {
      int hash = GetType().GetHashCode();
      return hash;
    }

    public override bool Equals(object obj) {
      SoundList other = obj as SoundList;
      if (other == null) return false;
      return true;
    }

    #endregion

    public void MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      uint tag;
      string field_name;
      while (input.ReadTag(out tag, out field_name)) {
        switch (tag) {
          case 0: {
            throw pb::InvalidProtocolBufferException.InvalidTag();
          }
          default: {
            if (pb::WireFormat.IsEndGroupTag(tag)) {
              return;
            }
            break;
          }
          case 10: {
            input.ReadString(ref this.Name);
            break;
          }
          case 18: {
            input.ReadString(ref this.Filename);
            break;
          }
          case 26: {
            input.ReadString(ref this.VolumeType);
            break;
          }
          case 32: {
            input.ReadInt32(ref this.Volume);
            break;
          }
          case 40: {
            input.ReadInt32(ref this.Pitch);
            break;
          }
          case 48: {
            input.ReadBool(ref this.Preload);
            break;
          }
          case 56: {
            input.ReadBool(ref this.Loop);
            break;
          }
          case 66: {
            input.ReadString(ref this.DestroyType);
            break;
          }
          case 74: {
            input.ReadString(ref this.OverlapType);
            break;
          }
          case 80: {
            input.ReadBool(ref this.PreloadSceneTitle);
            break;
          }
          case 88: {
            input.ReadBool(ref this.PreloadSceneHome);
            break;
          }
          case 96: {
            input.ReadBool(ref this.PreloadSceneGame);
            break;
          }
          case 104: {
            input.ReadBool(ref this.PreloadSceneResult);
            break;
          }
          case 112: {
            input.ReadBool(ref this.PreloadScenePvp);
            break;
          }
        }
      }
    }

  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class Enemy : IPbMessage {
    public Enemy() { }
    private static readonly Enemy defaultInstance = new Enemy();
    public static Enemy DefaultInstance {
      get { return defaultInstance; }
    }

    public int Id;

    public string Name = "";

    public int CardId;

    public string RaceType = "";

    public string Attribute = "";

    public string DriverParam = "";

    public int HitPoint;

    public int Agility;

    public int AttackRate;

    public int AttackDice;

    public int AttackCount;

    public int AttackAdjust;

    public string AttackSoundName = "";

    public int CriticalDamageRate;

    public string EnchantAttackName = "";

    public int EnchantAttackStatusRate;

    public string EnchantAttackCommand = "";

    public string EnchantAttackSoundName = "";

    public string SkillAttackName = "";

    public int SkillAttackRate;

    public string SkillAttackCommand = "";

    public string SkillAttackSoundName = "";

    public int DefenseDice;

    public int DefenseCount;

    public int DefenseAdjust;

    public string DefenseSoundName = "";

    public string EnchantDefenseName = "";

    public int EnchantDefenseStatusRate;

    public string EnchantDefenseCommand = "";

    public string EnchantDefenseSoundName = "";

    public int CriticalLotsCount;

    public int CriticalHitRate;

    public int Experience;

    public string DeadSoundName = "";

    public string DropItem255 = "";

    public string DropFang255 = "";

    public string DropGold = "";

    public int SleepRate;

    public int DeepsleepRate;

    public int MoveWaitCounter;

    public int MoveAdditonalTacticalPoint;

    public int AttackAdditionalTacticalPoint;

    public int PrefabId;

    public string Property = "";

    public string ExtraData = "";

    public int HaveItemNo;

    #region Lite runtime methods
    public override int GetHashCode() {
      int hash = GetType().GetHashCode();
      return hash;
    }

    public override bool Equals(object obj) {
      Enemy other = obj as Enemy;
      if (other == null) return false;
      return true;
    }

    #endregion

    public void MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      uint tag;
      string field_name;
      while (input.ReadTag(out tag, out field_name)) {
        switch (tag) {
          case 0: {
            throw pb::InvalidProtocolBufferException.InvalidTag();
          }
          default: {
            if (pb::WireFormat.IsEndGroupTag(tag)) {
              return;
            }
            break;
          }
          case 8: {
            input.ReadInt32(ref this.Id);
            break;
          }
          case 18: {
            input.ReadString(ref this.Name);
            break;
          }
          case 24: {
            input.ReadInt32(ref this.CardId);
            break;
          }
          case 34: {
            input.ReadString(ref this.RaceType);
            break;
          }
          case 42: {
            input.ReadString(ref this.Attribute);
            break;
          }
          case 50: {
            input.ReadString(ref this.DriverParam);
            break;
          }
          case 56: {
            input.ReadInt32(ref this.HitPoint);
            break;
          }
          case 64: {
            input.ReadInt32(ref this.Agility);
            break;
          }
          case 72: {
            input.ReadInt32(ref this.AttackRate);
            break;
          }
          case 80: {
            input.ReadInt32(ref this.AttackDice);
            break;
          }
          case 88: {
            input.ReadInt32(ref this.AttackCount);
            break;
          }
          case 96: {
            input.ReadInt32(ref this.AttackAdjust);
            break;
          }
          case 106: {
            input.ReadString(ref this.AttackSoundName);
            break;
          }
          case 112: {
            input.ReadInt32(ref this.CriticalDamageRate);
            break;
          }
          case 122: {
            input.ReadString(ref this.EnchantAttackName);
            break;
          }
          case 128: {
            input.ReadInt32(ref this.EnchantAttackStatusRate);
            break;
          }
          case 138: {
            input.ReadString(ref this.EnchantAttackCommand);
            break;
          }
          case 146: {
            input.ReadString(ref this.EnchantAttackSoundName);
            break;
          }
          case 154: {
            input.ReadString(ref this.SkillAttackName);
            break;
          }
          case 160: {
            input.ReadInt32(ref this.SkillAttackRate);
            break;
          }
          case 170: {
            input.ReadString(ref this.SkillAttackCommand);
            break;
          }
          case 178: {
            input.ReadString(ref this.SkillAttackSoundName);
            break;
          }
          case 184: {
            input.ReadInt32(ref this.DefenseDice);
            break;
          }
          case 192: {
            input.ReadInt32(ref this.DefenseCount);
            break;
          }
          case 200: {
            input.ReadInt32(ref this.DefenseAdjust);
            break;
          }
          case 210: {
            input.ReadString(ref this.DefenseSoundName);
            break;
          }
          case 218: {
            input.ReadString(ref this.EnchantDefenseName);
            break;
          }
          case 224: {
            input.ReadInt32(ref this.EnchantDefenseStatusRate);
            break;
          }
          case 234: {
            input.ReadString(ref this.EnchantDefenseCommand);
            break;
          }
          case 242: {
            input.ReadString(ref this.EnchantDefenseSoundName);
            break;
          }
          case 248: {
            input.ReadInt32(ref this.CriticalLotsCount);
            break;
          }
          case 256: {
            input.ReadInt32(ref this.CriticalHitRate);
            break;
          }
          case 264: {
            input.ReadInt32(ref this.Experience);
            break;
          }
          case 274: {
            input.ReadString(ref this.DeadSoundName);
            break;
          }
          case 282: {
            input.ReadString(ref this.DropItem255);
            break;
          }
          case 290: {
            input.ReadString(ref this.DropFang255);
            break;
          }
          case 298: {
            input.ReadString(ref this.DropGold);
            break;
          }
          case 304: {
            input.ReadInt32(ref this.SleepRate);
            break;
          }
          case 312: {
            input.ReadInt32(ref this.DeepsleepRate);
            break;
          }
          case 320: {
            input.ReadInt32(ref this.MoveWaitCounter);
            break;
          }
          case 328: {
            input.ReadInt32(ref this.MoveAdditonalTacticalPoint);
            break;
          }
          case 336: {
            input.ReadInt32(ref this.AttackAdditionalTacticalPoint);
            break;
          }
          case 344: {
            input.ReadInt32(ref this.PrefabId);
            break;
          }
          case 354: {
            input.ReadString(ref this.Property);
            break;
          }
          case 362: {
            input.ReadString(ref this.ExtraData);
            break;
          }
          case 368: {
            input.ReadInt32(ref this.HaveItemNo);
            break;
          }
        }
      }
    }

  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class Item : IPbMessage {
    public Item() { }
    private static readonly Item defaultInstance = new Item();
    public static Item DefaultInstance {
      get { return defaultInstance; }
    }

    public int Id;

    public int SortId;

    public string ItemCode = "";

    public string Mapchip = "";

    public string Name = "";

    public string Type = "";

    public string FittingType = "";

    public string Attribute = "";

    public string Param = "";

    public int AttackAdjust;

    public int DefenseAdjust;

    public int CirticalHitRate;

    public int Durability;

    public int MergeCount;

    public int Rarity;

    public int Price;

    public string SoundName = "";

    public bool IsPickup;

    public bool IsSwing;

    public bool IsUse;

    public bool IsDrop;

    public bool IsExclusive;

    public string ExtraType = "";

    public string Description = "";

    public int StackItemId;

    public int StackItemNum;

    public int DummyItemNameNo;

    public bool IsInExItem;

    public bool IsShot;

    #region Lite runtime methods
    public override int GetHashCode() {
      int hash = GetType().GetHashCode();
      return hash;
    }

    public override bool Equals(object obj) {
      Item other = obj as Item;
      if (other == null) return false;
      return true;
    }

    #endregion

    public void MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      uint tag;
      string field_name;
      while (input.ReadTag(out tag, out field_name)) {
        switch (tag) {
          case 0: {
            throw pb::InvalidProtocolBufferException.InvalidTag();
          }
          default: {
            if (pb::WireFormat.IsEndGroupTag(tag)) {
              return;
            }
            break;
          }
          case 8: {
            input.ReadInt32(ref this.Id);
            break;
          }
          case 16: {
            input.ReadInt32(ref this.SortId);
            break;
          }
          case 26: {
            input.ReadString(ref this.ItemCode);
            break;
          }
          case 34: {
            input.ReadString(ref this.Mapchip);
            break;
          }
          case 42: {
            input.ReadString(ref this.Name);
            break;
          }
          case 50: {
            input.ReadString(ref this.Type);
            break;
          }
          case 58: {
            input.ReadString(ref this.FittingType);
            break;
          }
          case 66: {
            input.ReadString(ref this.Attribute);
            break;
          }
          case 74: {
            input.ReadString(ref this.Param);
            break;
          }
          case 80: {
            input.ReadInt32(ref this.AttackAdjust);
            break;
          }
          case 88: {
            input.ReadInt32(ref this.DefenseAdjust);
            break;
          }
          case 96: {
            input.ReadInt32(ref this.CirticalHitRate);
            break;
          }
          case 104: {
            input.ReadInt32(ref this.Durability);
            break;
          }
          case 112: {
            input.ReadInt32(ref this.MergeCount);
            break;
          }
          case 120: {
            input.ReadInt32(ref this.Rarity);
            break;
          }
          case 128: {
            input.ReadInt32(ref this.Price);
            break;
          }
          case 138: {
            input.ReadString(ref this.SoundName);
            break;
          }
          case 144: {
            input.ReadBool(ref this.IsPickup);
            break;
          }
          case 152: {
            input.ReadBool(ref this.IsSwing);
            break;
          }
          case 160: {
            input.ReadBool(ref this.IsUse);
            break;
          }
          case 168: {
            input.ReadBool(ref this.IsDrop);
            break;
          }
          case 176: {
            input.ReadBool(ref this.IsExclusive);
            break;
          }
          case 186: {
            input.ReadString(ref this.ExtraType);
            break;
          }
          case 194: {
            input.ReadString(ref this.Description);
            break;
          }
          case 200: {
            input.ReadInt32(ref this.StackItemId);
            break;
          }
          case 208: {
            input.ReadInt32(ref this.StackItemNum);
            break;
          }
          case 216: {
            input.ReadInt32(ref this.DummyItemNameNo);
            break;
          }
          case 224: {
            input.ReadBool(ref this.IsInExItem);
            break;
          }
          case 232: {
            input.ReadBool(ref this.IsShot);
            break;
          }
        }
      }
    }

  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class ItemName : IPbMessage {
    public ItemName() { }
    private static readonly ItemName defaultInstance = new ItemName();
    public static ItemName DefaultInstance {
      get { return defaultInstance; }
    }

    public int Id;

    public string Name = "";

    #region Lite runtime methods
    public override int GetHashCode() {
      int hash = GetType().GetHashCode();
      return hash;
    }

    public override bool Equals(object obj) {
      ItemName other = obj as ItemName;
      if (other == null) return false;
      return true;
    }

    #endregion

    public void MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      uint tag;
      string field_name;
      while (input.ReadTag(out tag, out field_name)) {
        switch (tag) {
          case 0: {
            throw pb::InvalidProtocolBufferException.InvalidTag();
          }
          default: {
            if (pb::WireFormat.IsEndGroupTag(tag)) {
              return;
            }
            break;
          }
          case 8: {
            input.ReadInt32(ref this.Id);
            break;
          }
          case 18: {
            input.ReadString(ref this.Name);
            break;
          }
        }
      }
    }

  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class ItemNameDict : IPbMessage {
    public ItemNameDict() { }
    private static readonly ItemNameDict defaultInstance = new ItemNameDict();
    public static ItemNameDict DefaultInstance {
      get { return defaultInstance; }
    }

    #region Nested types
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public static partial class Types {
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
      public sealed partial class List : IPbMessage {
        public List() { }
        private static readonly List defaultInstance = new List();
        public static List DefaultInstance {
          get { return defaultInstance; }
        }

        public global::Master.ItemName[] List_;

        #region Lite runtime methods
        public override int GetHashCode() {
          int hash = GetType().GetHashCode();
          return hash;
        }

        public override bool Equals(object obj) {
          List other = obj as List;
          if (other == null) return false;
          return true;
        }

        #endregion

        public void MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
          uint tag;
          string field_name;
          while (input.ReadTag(out tag, out field_name)) {
            switch (tag) {
              case 0: {
                throw pb::InvalidProtocolBufferException.InvalidTag();
              }
              default: {
                if (pb::WireFormat.IsEndGroupTag(tag)) {
                  return;
                }
                break;
              }
              case 10: {
                Test.Input_ReadMessageArray(tag, out this.List_);
                break;
              }
            }
          }
        }

      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
      public sealed partial class DictEntry : IPbMessage {
        public DictEntry() { }
        private static readonly DictEntry defaultInstance = new DictEntry();
        public static DictEntry DefaultInstance {
          get { return defaultInstance; }
        }

        public string Key = "";

        public global::Master.ItemNameDict.Types.List Value;

        #region Lite runtime methods
        public override int GetHashCode() {
          int hash = GetType().GetHashCode();
          return hash;
        }

        public override bool Equals(object obj) {
          DictEntry other = obj as DictEntry;
          if (other == null) return false;
          return true;
        }

        #endregion

        public void MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
          uint tag;
          string field_name;
          while (input.ReadTag(out tag, out field_name)) {
            switch (tag) {
              case 0: {
                throw pb::InvalidProtocolBufferException.InvalidTag();
              }
              default: {
                if (pb::WireFormat.IsEndGroupTag(tag)) {
                  return;
                }
                break;
              }
              case 10: {
                input.ReadString(ref this.Key);
                break;
              }
              case 18: {
                global::Master.ItemNameDict.Types.List builder = new global::Master.ItemNameDict.Types.List();
                Test.Input_ReadMessage(builder, extensionRegistry);
                Value = builder;
                break;
              }
            }
          }
        }

      }

    }
    #endregion

    public global::Master.ItemNameDict.Types.DictEntry[] Dict;

    #region Lite runtime methods
    public override int GetHashCode() {
      int hash = GetType().GetHashCode();
      return hash;
    }

    public override bool Equals(object obj) {
      ItemNameDict other = obj as ItemNameDict;
      if (other == null) return false;
      return true;
    }

    #endregion

    public void MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      uint tag;
      string field_name;
      while (input.ReadTag(out tag, out field_name)) {
        switch (tag) {
          case 0: {
            throw pb::InvalidProtocolBufferException.InvalidTag();
          }
          default: {
            if (pb::WireFormat.IsEndGroupTag(tag)) {
              return;
            }
            break;
          }
          case 10: {
            Test.Input_ReadMessageArray(tag, out this.Dict);
            break;
          }
        }
      }
    }

  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class Trap : IPbMessage {
    public Trap() { }
    private static readonly Trap defaultInstance = new Trap();
    public static Trap DefaultInstance {
      get { return defaultInstance; }
    }

    public int Id;

    public string TrapCode = "";

    public string Name = "";

    public string DriverName = "";

    public string DriverParameter = "";

    public int Probability;

    public string SoundName = "";

    #region Lite runtime methods
    public override int GetHashCode() {
      int hash = GetType().GetHashCode();
      return hash;
    }

    public override bool Equals(object obj) {
      Trap other = obj as Trap;
      if (other == null) return false;
      return true;
    }

    #endregion

    public void MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      uint tag;
      string field_name;
      while (input.ReadTag(out tag, out field_name)) {
        switch (tag) {
          case 0: {
            throw pb::InvalidProtocolBufferException.InvalidTag();
          }
          default: {
            if (pb::WireFormat.IsEndGroupTag(tag)) {
              return;
            }
            break;
          }
          case 8: {
            input.ReadInt32(ref this.Id);
            break;
          }
          case 18: {
            input.ReadString(ref this.Name);
            break;
          }
          case 26: {
            input.ReadString(ref this.TrapCode);
            break;
          }
          case 34: {
            input.ReadString(ref this.DriverName);
            break;
          }
          case 42: {
            input.ReadString(ref this.DriverParameter);
            break;
          }
          case 48: {
            input.ReadInt32(ref this.Probability);
            break;
          }
          case 58: {
            input.ReadString(ref this.SoundName);
            break;
          }
        }
      }
    }

  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class StringData : IPbMessage {
    public StringData() { }
    private static readonly StringData defaultInstance = new StringData();
    public static StringData DefaultInstance {
      get { return defaultInstance; }
    }

    public string Id = "";

    public string Text = "";

    #region Lite runtime methods
    public override int GetHashCode() {
      int hash = GetType().GetHashCode();
      return hash;
    }

    public override bool Equals(object obj) {
      StringData other = obj as StringData;
      if (other == null) return false;
      return true;
    }

    #endregion

    public void MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      uint tag;
      string field_name;
      while (input.ReadTag(out tag, out field_name)) {
        switch (tag) {
          case 0: {
            throw pb::InvalidProtocolBufferException.InvalidTag();
          }
          default: {
            if (pb::WireFormat.IsEndGroupTag(tag)) {
              return;
            }
            break;
          }
          case 10: {
            input.ReadString(ref this.Id);
            break;
          }
          case 18: {
            input.ReadString(ref this.Text);
            break;
          }
        }
      }
    }

  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class SoloDuel : IPbMessage {
    public SoloDuel() { }
    private static readonly SoloDuel defaultInstance = new SoloDuel();
    public static SoloDuel DefaultInstance {
      get { return defaultInstance; }
    }

    public int StageId;

    public int EnemyNo;

    public int Level;

    public int FangId;

    public int Hp;

    public int Attack;

    public int Defense;

    public int Exp;

    #region Lite runtime methods
    public override int GetHashCode() {
      int hash = GetType().GetHashCode();
      return hash;
    }

    public override bool Equals(object obj) {
      SoloDuel other = obj as SoloDuel;
      if (other == null) return false;
      return true;
    }

    #endregion

    public void MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      uint tag;
      string field_name;
      while (input.ReadTag(out tag, out field_name)) {
        switch (tag) {
          case 0: {
            throw pb::InvalidProtocolBufferException.InvalidTag();
          }
          default: {
            if (pb::WireFormat.IsEndGroupTag(tag)) {
              return;
            }
            break;
          }
          case 8: {
            input.ReadInt32(ref this.StageId);
            break;
          }
          case 16: {
            input.ReadInt32(ref this.EnemyNo);
            break;
          }
          case 24: {
            input.ReadInt32(ref this.Level);
            break;
          }
          case 32: {
            input.ReadInt32(ref this.FangId);
            break;
          }
          case 40: {
            input.ReadInt32(ref this.Hp);
            break;
          }
          case 48: {
            input.ReadInt32(ref this.Attack);
            break;
          }
          case 56: {
            input.ReadInt32(ref this.Defense);
            break;
          }
          case 64: {
            input.ReadInt32(ref this.Exp);
            break;
          }
        }
      }
    }

  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class RoomInfo : IPbMessage {
    public RoomInfo() { }
    private static readonly RoomInfo defaultInstance = new RoomInfo();
    public static RoomInfo DefaultInstance {
      get { return defaultInstance; }
    }

    public string Id = "";

    public int Width;

    public int Height;

    public int Attribute;

    public int Direction;

    #region Lite runtime methods
    public override int GetHashCode() {
      int hash = GetType().GetHashCode();
      return hash;
    }

    public override bool Equals(object obj) {
      RoomInfo other = obj as RoomInfo;
      if (other == null) return false;
      return true;
    }

    #endregion

    public void MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      uint tag;
      string field_name;
      while (input.ReadTag(out tag, out field_name)) {
        switch (tag) {
          case 0: {
            throw pb::InvalidProtocolBufferException.InvalidTag();
          }
          default: {
            if (pb::WireFormat.IsEndGroupTag(tag)) {
              return;
            }
            break;
          }
          case 10: {
            input.ReadString(ref this.Id);
            break;
          }
          case 16: {
            input.ReadInt32(ref this.Width);
            break;
          }
          case 24: {
            input.ReadInt32(ref this.Height);
            break;
          }
          case 32: {
            input.ReadInt32(ref this.Attribute);
            break;
          }
          case 40: {
            input.ReadInt32(ref this.Direction);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
